# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/compraprogramada
spring.datasource.username=compra
spring.datasource.password=compra123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# COTAHIST
cotahist.diretorio=./cotacoes

# Motor de Compra - executa as 9h nos dias 5, 15 e 25
# motor.compra.cron=0 0 9 5,15,25 * ?

# Alterar o motor de compra para executar a cada 5 minutos
motor.compra.cron=0 */5 * * * ?

# Kafka Topics
kafka.topic.ir=ir-eventos

# Async thread pool
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
